import { WalletState } from "@/types";

export const MOCK_WALLET: WalletState = {
  account_id: "SEY-ACC-002",
  account_holder: "Kumari Perera",
  linked_sender: "Nimal Fernando",
  total_balance_lkr: 245000,
  last_remittance: {
    amount_lkr: 245000,
    amount_gbp: 600,
    fx_rate: 408.3,
    date: "1 May 2026",
    provider: "Tempo",
  },
  buckets: [
    {
      bucket_id: "bucket_school",
      label: "School",
      allocation_pct: 40,
      balance_lkr: 98000,
      spent_lkr: 26600,
      icon: "school",
      colour: "blue",
    },
    {
      bucket_id: "bucket_household",
      label: "Household",
      allocation_pct: 40,
      balance_lkr: 71500,
      spent_lkr: 26500,
      icon: "household",
      colour: "emerald",
    },
    {
      bucket_id: "bucket_savings",
      label: "Savings",
      allocation_pct: 20,
      balance_lkr: 49000,
      spent_lkr: 0,
      icon: "savings",
      colour: "violet",
    },
  ],
  recent_transactions: [
    {
      transaction_id: "tx-001",
      account_id: "SEY-ACC-002",
      bucket_id: "bucket_household",
      bucket_label: "Household",
      amount_lkr: 4200,
      merchant: "Keells Super",
      timestamp: "2026-05-15T14:30:00Z",
      type: "debit",
    },
    {
      transaction_id: "tx-002",
      account_id: "SEY-ACC-002",
      bucket_id: "bucket_school",
      bucket_label: "School",
      amount_lkr: 15000,
      merchant: "Royal College - Term Fee",
      timestamp: "2026-05-14T09:00:00Z",
      type: "debit",
    },
    {
      transaction_id: "tx-003",
      account_id: "SEY-ACC-002",
      bucket_id: "bucket_household",
      bucket_label: "Household",
      amount_lkr: 3800,
      merchant: "Ceylon Electricity Board",
      timestamp: "2026-05-13T11:20:00Z",
      type: "debit",
    },
    {
      transaction_id: "tx-004",
      account_id: "SEY-ACC-002",
      bucket_id: "bucket_household",
      bucket_label: "Household",
      amount_lkr: 2100,
      merchant: "Dialog Axiata - Mobile",
      timestamp: "2026-05-12T16:45:00Z",
      type: "debit",
    },
    {
      transaction_id: "tx-005",
      account_id: "SEY-ACC-002",
      bucket_id: "bucket_school",
      bucket_label: "School",
      amount_lkr: 8500,
      merchant: "Vijitha Yapa Bookshop",
      timestamp: "2026-05-11T10:15:00Z",
      type: "debit",
    },
    {
      transaction_id: "tx-006",
      account_id: "SEY-ACC-002",
      bucket_id: "bucket_household",
      bucket_label: "Household",
      amount_lkr: 6800,
      merchant: "Softlogic Glomark",
      timestamp: "2026-05-10T13:00:00Z",
      type: "debit",
    },
    {
      transaction_id: "tx-007",
      account_id: "SEY-ACC-002",
      bucket_id: "bucket_household",
      bucket_label: "Household",
      amount_lkr: 1500,
      merchant: "PickMe Ride",
      timestamp: "2026-05-09T08:30:00Z",
      type: "debit",
    },
    {
      transaction_id: "tx-008",
      account_id: "SEY-ACC-002",
      bucket_id: "bucket_school",
      bucket_label: "School",
      amount_lkr: 3100,
      merchant: "Tuition - Mrs. Perera",
      timestamp: "2026-05-08T15:00:00Z",
      type: "debit",
    },
  ],
};
